### ISSUE TITLE
 Hello, author. I am very interested in your project, and I have successfully built and run it. However, I have some doubts about the next steps for expansion. I'm wondering if you can help me with that.

### ISSUE THREAD

**Issue by Destiny-0226** [qis/horus#3]
Certainly, you've successfully compiled the plugin and applied it in OBS, and you can see the recognized image correctly in OBS. Regarding the code you mentioned in the "hid" class, it appears to be related to sending mouse movement commands via some transmission method rather than direct mouse movement. Is that correct?

I have my own hardware with its dedicated DLL, lib libraries, and corresponding header files. Can I modify the content of the "void hid::move(std::int16_t x, std.int16_t y) noexcept" function during the plugin compilation to replace it with commands from my own library to achieve direct mouse movement? For example:
void hid::move(std::int16_t x, std::int16_t y) noexcept
{
  if (!x && !y) {
    return;
  }
  M_MoveR2(hdl, x, y);
}

**Comment by qis** [comment]
Yep. That's mentioned in the README. Due to legal reasons, I can't release a working version of the cheat. The parts you have compiled don't give you a competitive advantage.

Just replace it with either a RPI with OTG drivers and a small application that sends USB HID commands, or write a Windows driver that simulates or filters a HID device.

**Comment by qis** [comment]
By the way, the next steps for me in 20204 (not rushing it) are:

1. Update external cheat (separate project).
2. Decode component system and get outlines.
3. Train a NN to detect the true outlines.
4. Train a NN to predict player movements.
5. Possibly train a NN to detect heroes, distance and vertical angle?
